[package]
name = "article-history-rs"
version = "0.1.0"
authors = ["Daniel Glus <danielhglus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dtparse = "1.2.0"
parse_wiki_text = "0.1.5"
chrono = "0.4.19"
